language: objective-c
os: osx
osx_image: xcode10

env:
  global:
    - MAKEFLAGS="-j9"

git:
  submodules: false
  depth: false

branches:
  only:
  - develop

before_install:
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - git submodule update --init
  - brew install dpkg ldid

script: make
